name: Deploy To Production
# Secrets: SSH_PRIVATE_KEY, SSH_HOST, SSH_USER, SSH_PATH

on:
  workflow_dispatch:
  release:
    types: [published, deleted]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # Get Latest Release
      - name: Latest Release
        id: latest
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          #node-version: "14"
          node-version: "16"

      # Install NPM Dependencies
      - name: NPM Install
        run: npm ci
      
      # Build With Laravel Mix
      - name: Build With Laravel Mix
        run: npx mix --production
      
      # Build with Grunt
      #- name: Build with Grunt
      #  run: grunt dist
      
      # Add SSH Private Key
      - name: Add Private SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy With Rsync
      - name: Deploy With Rsync
        run: |
          rsync -azh --delete-after --exclude={"/public_html/system/user/config/config.php","/public_html/uploads/","/node_modules/","/.git/","/.github/","/src/","README.md","package.json","package-lock.json","webpack.mix.js",".gitignore"} -e "ssh -p 22 -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
