name: Deploy To Staging
# Secrets: SSH_PRIVATE_KEY, STAGING_SSH_HOST, STAGING_SSH_USER, STAGING_SSH_PATH

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          #node-version: "14"
          node-version: "16"

      # Install NPM Dependencies
      - name: NPM Install
        run: npm ci

      # Build With Laravel Mix
      - name: Build With Laravel Mix
        run: npx mix --production
      
      # Build With Grunt
      #- name: Build With Grunt
      #  run: grunt dist

      # Add SSH Private Key
      - name: Add Private SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy With Rsync
      - name: Deploy With Rsync
        run: |
          rsync -azh --delete-after --exclude={"/public_html/system/user/config/config.php","/public_html/uploads/","/node_modules/","/.git/","/.github/","/src/","README.md","package.json","package-lock.json","webpack.mix.js",".gitignore"} -e "ssh -p 22 -o StrictHostKeyChecking=no" ./ ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST }}:${{ secrets.STAGING_SSH_PATH }}
